name: Update prebuilt debs
on:
  push:
  schedule:
    - cron: '7 8 * * *'
jobs:
  update-prebuilt-debs:
    runs-on: ubuntu-latest
    container:
      image: debian:testing-slim
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        GPG_KEY: ${{ secrets.GPG_KEY }}
    steps:
      - name: Update prebuilt debs
        shell: bash
        run: |
          log() {
              echo -e "\033[0;32m${@}\033[0m"
          }
          apt-get -y update
          apt-get -y install --no-install-recommends \
              apt-utils \
              curl \
              ca-certificates \
              git \
              openssh-client
          log "Exporting SSH socket"
          export SSH_AUTH_SOCK="/tmp/ssh-agent.sock"
          log "Starting SSH agent"
          ssh-agent -a "${SSH_AUTH_SOCK}"
          log "Adding SSH key"
          ssh-add - <<< "${SSH_KEY}"
          log "Adding github.com to known hosts"
          mkdir -p /root/.ssh
          ssh-keyscan github.com > /root/.ssh/known_hosts
          chmod -R go-rwx /root/.ssh
          git clone --depth 1 git@github.com:lmd-linux/lmd-linux.github.io.git
          cd lmd-linux.github.io

          HEROIC_URL=$(curl -sL https://api.github.com/repos/Heroic-Games-Launcher/HeroicGamesLauncher/releases/latest | grep '"browser_download_url"' | grep '.deb"' | cut -d '"' -f 4)
          echo "Heroic URL: ${HEROIC_URL}"
          HEROIC_PATH="pool/stable/amd64/$(basename ${HEROIC_URL})"
          if [ -f "${HEROIC_PATH}" ]; then
              echo "${HEROIC_PATH} already exists"
          else
              rm -f pool/stable/amd64/heroic_*_amd64.deb
              curl -sL -o ${HEROIC_PATH} ${HEROIC_URL}
          fi

          if ! [[ $(git status --porcelain) ]]; then
              echo "No changes"
              exit
          fi
          log "Setting user name and email"
          git config user.name "lmd Linux"
          git config user.email lmd.linux@gmail.com
          git add .
          git commit -m "Update heroic"
          git push
